In [2]:
# Desafío 1#
import numpy as np 

array1=np.linspace(start= 1,
            stop=50,
            num=40,
            dtype=int
           )

In [3]:
# Desafío 1#
array2=np.linspace(start= 50,
            stop=150,
            num=40,
            dtype=int
           )
print(array2)

[ 50  52  55  57  60  62  65  67  70  73  75  78  80  83  85  88  91  93
  96  98 101 103 106 108 111 114 116 119 121 124 126 129 132 134 137 139
 142 144 147 150]

In [ ]:
# Desafío 2#

for i in array1:
    if i%2==0:
        print(i, "es un numero par")

In [ ]:
# Desafío 3#
cont=0
for i in array2:
    if i%2==0 or i%3==0 :
        cont+=1 
        print(i, "es un numero divisible por 2 o por 3")
print("Los números divisibles por 2 o por 3 son: ", cont)

In [ ]:
# Desafío 3#
cont=0
for i in array2:
    if i%2==0 or i%3==0 :
        cont+=1 
        print(i, "es un numero divisible por 2 o por 3")
print("Los números divisibles por 2 o por 3 son: ", cont)

In [43]:
# Desafío 3# (REVISAR)
cont=0
for i in array2:
    if i%3==0 and i%2!=0 :
        cont+=1 
        print(i, "es un numero divisible por 3, pero no por 2")
print("Los números divisibles por 3 y no por 2 son: ", cont)

57 es un numero divisible por 3, pero no por 2
75 es un numero divisible por 3, pero no por 2
93 es un numero divisible por 3, pero no por 2
111 es un numero divisible por 3, pero no por 2
129 es un numero divisible por 3, pero no por 2
147 es un numero divisible por 3, pero no por 2
Los números divisibles por 3 y no por 2 son:  6

In [44]:
# Desafío 3#
cont=0
for i in array2:
    if i%2==0 and i%3==0 :
        cont+=1 
        print(i, "es un numero divisible por 2 y por 3")
print("Los números divisibles por 2 o por 3 son: ", cont)

60 es un numero divisible por 2 y por 3
78 es un numero divisible por 2 y por 3
96 es un numero divisible por 2 y por 3
108 es un numero divisible por 2 y por 3
114 es un numero divisible por 2 y por 3
126 es un numero divisible por 2 y por 3
132 es un numero divisible por 2 y por 3
144 es un numero divisible por 2 y por 3
150 es un numero divisible por 2 y por 3
Los números divisibles por 2 o por 3 son:  9

In [42]:
# Desafío 3#  (REVISAR)
cont=0
for i in array2:
    if i%3!=0 and i%2!=0 :
        cont+=1 
        print(i, "es un numero no divisible por 2 y por 3")
print("Los números no divisibles por 2 y  por 3 son: ", cont)

55 es un numero no divisible por 2 y por 3
65 es un numero no divisible por 2 y por 3
67 es un numero no divisible por 2 y por 3
73 es un numero no divisible por 2 y por 3
83 es un numero no divisible por 2 y por 3
85 es un numero no divisible por 2 y por 3
91 es un numero no divisible por 2 y por 3
101 es un numero no divisible por 2 y por 3
103 es un numero no divisible por 2 y por 3
119 es un numero no divisible por 2 y por 3
121 es un numero no divisible por 2 y por 3
137 es un numero no divisible por 2 y por 3
139 es un numero no divisible por 2 y por 3
Los números no divisibles por 2 y  por 3 son:  13

In [47]:
# Desafío 3 (integrado)# 
cont1=0
cont2=0
cont3=0
cont4=0

for i in array2:
    if i%2==0 or i%3==0 :
        cont1+=1 
        print(i, "es un numero divisible por 2 o por 3")
        print(" ")
    if i%2==0 and i%3==0 :
        cont2+=1 
        print(i, "es un numero divisible por 2 y por 3")
        print(" ")       
    if i%3==0 and i%2!=0 :
        cont3+=1 
        print(i, "es un numero divisible por 3, pero no por 2")
        print("  ")
    if i%3!=0 and i%2!=0 :
        cont4+=1 
        print(" ")
        print(i, "es un numero no divisible por 2 y por 3")
  
        
print("Los números divisibles por 2 o por 3 son: ", cont1) 
print("Los números divisibles por 2 y por 3 son: ", cont2) 
print("Los números divisibles por 3 y no por 2 son: ", cont3)        
print("Los números no divisibles por 2 y  por 3 son: ", cont4)

50 es un numero divisible por 2 o por 3

52 es un numero divisible por 2 o por 3


55 es un numero no divisible por 2 y por 3
57 es un numero divisible por 2 o por 3

57 es un numero divisible por 3, pero no por 2

60 es un numero divisible por 2 o por 3

60 es un numero divisible por 2 y por 3

62 es un numero divisible por 2 o por 3


65 es un numero no divisible por 2 y por 3

67 es un numero no divisible por 2 y por 3
70 es un numero divisible por 2 o por 3


73 es un numero no divisible por 2 y por 3
75 es un numero divisible por 2 o por 3

75 es un numero divisible por 3, pero no por 2

78 es un numero divisible por 2 o por 3

78 es un numero divisible por 2 y por 3

80 es un numero divisible por 2 o por 3


83 es un numero no divisible por 2 y por 3

85 es un numero no divisible por 2 y por 3
88 es un numero divisible por 2 o por 3


91 es un numero no divisible por 2 y por 3
93 es un numero divisible por 2 o por 3

93 es un numero divisible por 3, pero no por 2

96 es un numero divisible por 2 o por 3

96 es un numero divisible por 2 y por 3

98 es un numero divisible por 2 o por 3


101 es un numero no divisible por 2 y por 3

103 es un numero no divisible por 2 y por 3
106 es un numero divisible por 2 o por 3

108 es un numero divisible por 2 o por 3

108 es un numero divisible por 2 y por 3

111 es un numero divisible por 2 o por 3

111 es un numero divisible por 3, pero no por 2

114 es un numero divisible por 2 o por 3

114 es un numero divisible por 2 y por 3

116 es un numero divisible por 2 o por 3


119 es un numero no divisible por 2 y por 3

121 es un numero no divisible por 2 y por 3
124 es un numero divisible por 2 o por 3

126 es un numero divisible por 2 o por 3

126 es un numero divisible por 2 y por 3

129 es un numero divisible por 2 o por 3

129 es un numero divisible por 3, pero no por 2

132 es un numero divisible por 2 o por 3

132 es un numero divisible por 2 y por 3

134 es un numero divisible por 2 o por 3


137 es un numero no divisible por 2 y por 3

139 es un numero no divisible por 2 y por 3
142 es un numero divisible por 2 o por 3

144 es un numero divisible por 2 o por 3

144 es un numero divisible por 2 y por 3

147 es un numero divisible por 2 o por 3

147 es un numero divisible por 3, pero no por 2

150 es un numero divisible por 2 o por 3

150 es un numero divisible por 2 y por 3

Los números divisibles por 2 o por 3 son:  27
Los números divisibles por 2 y por 3 son:  9
Los números divisibles por 3 y no por 2 son:  6
Los números no divisibles por 2 y  por 3 son:  13

In [13]:
# Desafío 4#
for i in range(100):
    print(i**2) 
# I no está definida, debe ser reemplazada por i#

0
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801

In [41]:
# Desafío 5#

import pandas as pd
import numpy as np

df=pd.read_csv("flights.csv")
media_pas=df["passengers"].mean()

df["underperforming"]=0 

for indice,fila in df.iterrows():
    if fila['passengers']<=media_pas:
        df.at[indice,'underperforming'] =1
    
 
    
print(media_pas)
print(df)

280.2986111111111
     year      month  passengers  underperforming
0    1949    January         112                1
1    1949   February         118                1
2    1949      March         132                1
3    1949      April         129                1
4    1949        May         121                1
5    1949       June         135                1
6    1949       July         148                1
7    1949     August         148                1
8    1949  September         136                1
9    1949    October         119                1
10   1949   November         104                1
11   1949   December         118                1
12   1950    January         115                1
13   1950   February         126                1
14   1950      March         141                1
15   1950      April         135                1
16   1950        May         125                1
17   1950       June         149                1
18   1950       July         170                1
19   1950     August         170                1
20   1950  September         158                1
21   1950    October         133                1
22   1950   November         114                1
23   1950   December         140                1
24   1951    January         145                1
25   1951   February         150                1
26   1951      March         178                1
27   1951      April         163                1
28   1951        May         172                1
29   1951       June         178                1
..    ...        ...         ...              ...
114  1958       July         491                0
115  1958     August         505                0
116  1958  September         404                0
117  1958    October         359                0
118  1958   November         310                0
119  1958   December         337                0
120  1959    January         360                0
121  1959   February         342                0
122  1959      March         406                0
123  1959      April         396                0
124  1959        May         420                0
125  1959       June         472                0
126  1959       July         548                0
127  1959     August         559                0
128  1959  September         463                0
129  1959    October         407                0
130  1959   November         362                0
131  1959   December         405                0
132  1960    January         417                0
133  1960   February         391                0
134  1960      March         419                0
135  1960      April         461                0
136  1960        May         472                0
137  1960       June         535                0
138  1960       July         622                0
139  1960     August         606                0
140  1960  September         508                0
141  1960    October         461                0
142  1960   November         390                0
143  1960   December         432                0

[144 rows x 4 columns]

In [22]:
# Desafío 6#

import pandas as pd
import numpy as np

df=pd.read_csv("flights.csv")
media_pas=df["passengers"].mean()
ds_pas=df["passengers"].std()

df["outliers"]=0 
cont=0
for indice,fila in df.iterrows():
    if fila['passengers']< (media_pas-ds_pas) or fila['passengers'] >(media_pas+ds_pas) :
        df.at[indice,'outliers'] =1
        cont+=1
        
print("El numero de registros como casos extremos es: ", cont) #El modo más sencillo es con un contador#
data_filter = df[df['outliers'] == 1] 
print ("El numero de registros como casos extremos es: ", data_filter['outliers'].count())#otra forma con count#
df.set_index(["outliers", "passengers"]).count(level="outliers")#Otra forma es usando set_index #

El numero de registros como casos extremos es:  53
El numero de registros como casos extremos es:  53

          year  month
outliers
0           91     91
1           53     53